=== eduardofroes/LidaWithWorldServer3D/experimentsExecution/configs/LidaXMLSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://ccrg.cs.memphis.edu/LidaXMLSchema" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://ccrg.cs.memphis.edu/LidaXMLSchema">
    <complexType name="module">
    	<sequence>
    		<element name="class" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="submodules" type="tns:modules"
    			maxOccurs="1" minOccurs="0">
    		</element>
    		<element name="associatedmodule" type="tns:associatedmodule"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    		<element name="param" type="tns:param" maxOccurs="unbounded"
    			minOccurs="0">
    		</element>
    		<element name="taskspawner" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="initialTasks" type="tns:tasks" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="initializerclass" type="string" maxOccurs="1"
    			minOccurs="0">
    		</element>
    	</sequence>
    	<attribute name="name" type="string" use="required"></attribute>
    </complexType>





    <complexType name="modules">
    	<sequence>
    		<element name="module" type="tns:module" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="taskspawners">
    	<sequence>
    		<element name="taskspawner" type="tns:taskspawner" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <element name="lida" type="tns:lida"></element>
    
    <complexType name="lida">
    	<sequence>
            <element name="globalparams" type="tns:params"
            	maxOccurs="1" minOccurs="0">
            </element>
            <element name="taskmanager" type="tns:taskmanager"
    			maxOccurs="1" minOccurs="1">
    		</element>
    		<element name="taskspawners" type="tns:taskspawners"
    			maxOccurs="1" minOccurs="1">
    		</element>
    		<element name="submodules" type="tns:modules" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="listeners" type="tns:listeners" maxOccurs="1"
    			minOccurs="0">
    		</element>
    	</sequence>
    </complexType>

    <complexType name="param">
    	<simpleContent>
    		<extension base="string">
    			<attribute name="name" type="string" use="required"></attribute>
    			<attribute name="type" use="optional">
    				<simpleType>
    					<restriction base="string">
    						<enumeration value="int"></enumeration>
    						<enumeration value="double"></enumeration>
    						<enumeration value="string"></enumeration>
    						<enumeration value="boolean"></enumeration>
    					</restriction>
    				</simpleType>
    			</attribute>
    		</extension>
    	</simpleContent>
    </complexType>

    <complexType name="listener">
    	<sequence>
    		<element name="listenertype" type="string" maxOccurs="1" minOccurs="1"></element>
    		<element name="modulename" type="string" maxOccurs="1" minOccurs="1"></element>
    		<element name="listenername" type="string" maxOccurs="1" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="listeners">
    	<sequence>
    		<element name="listener" type="tns:listener" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="taskmanager">
    	<sequence>
    		<element name="param" type="tns:param" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>

    <complexType name="associatedmodule">
       <simpleContent>
      <extension base="string">
    	<attribute name="function" type="string" use="optional"></attribute>
      </extension>
    </simpleContent>
    </complexType>

    <complexType name="task">
        	<sequence>
    		<element name="tasktype" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="ticksperrun" type="int" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="param" type="tns:param" maxOccurs="unbounded"
    			minOccurs="0">
    		</element>
    	</sequence>
    	<attribute name="name" type="string" use="required"></attribute>
    </complexType>

    <complexType name="tasks">
    	<sequence>
    		<element name="task" type="tns:task" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="taskspawner">
    <sequence>
        		<element name="class" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="param" type="tns:param" maxOccurs="unbounded"
    			minOccurs="0">
    		</element>
    	</sequence>
    	<attribute name="name" type="string" use="required"></attribute>
    
    </complexType>

    <complexType name="params">
    	<sequence>
    		<element name="param" type="tns:param" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>
</schema>

=== eduardofroes/LidaWithWorldServer3D/configs/Agent.xml
<?xml version="1.0" encoding="UTF-8"?><!--   Copyright (c) 2009, 2011 The University of Memphis.  All rights reserved.    This program and the accompanying materials are made available    under the terms of the LIDA Software Framework Non-Commercial License v1.0    which accompanies this distribution, and is available at   http://ccrg.cs.memphis.edu/assets/papers/2010/LIDA-framework-non-commercial-v1.0.pdf--><lida xmlns="http://ccrg.cs.memphis.edu/LidaXMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"      xsi:schemaLocation="http://ccrg.cs.memphis.edu/LidaXMLSchema LidaXMLSchema.xsd ">    <taskmanager>        <param name="taskManager.tickDuration" type="int">1 </param>        <param name="taskManager.maxNumberOfThreads" type="int"> 100</param>    </taskmanager>    <taskspawners>        <taskspawner name="defaultTS">            <class>edu.memphis.ccrg.lida.framework.tasks.TaskSpawnerImpl</class>        </taskspawner>    </taskspawners>    <submodules>         <module name="Environment">            <class>modules.Environment</class>            <param name="environment.ticksPerRun" type="int">20</param>            <param name="height" type="int"> 10 </param>            <param name="width" type="int">10 </param>            <taskspawner>defaultTS</taskspawner>        </module>        <module name="SensoryMemory">            <class>modules.SensoryMemory</class>            <associatedmodule>Environment</associatedmodule>            <taskspawner>defaultTS</taskspawner>            <initialTasks>                <task name="backgroundTask">                    <tasktype>SensoryMemoryBackgroundTask</tasktype>                    <ticksperrun>5</ticksperrun>                </task>            </initialTasks>        </module>        <module name="PerceptualAssociativeMemory">            <class>edu.memphis.ccrg.lida.pam.PerceptualAssociativeMemoryImpl</class>            <param name="pam.upscale" type="double">.7 </param>            <param name="pam.downscale" type="double">.6 </param>            <param name="pam.selectivity" type="double">.5 </param>            <param name="pam.perceptThreshold" type="double">0.7</param>            <param name="pam.excitationTicksPerRun" type="int">1</param>            <param name="pam.propagationTicksPerRun" type="int">1</param>            <param name="pam.propagateActivationThreshold" type="double">0.05</param>            <param name="nodes">                thingDirection,thingCollided,thingToGet,wallFront,rotate,random,delivery            </param>            <taskspawner>defaultTS</taskspawner>            <initialTasks>                <task name="ThingDirectionDetector">                    <tasktype>ThingDirectionDetector</tasktype>                    <ticksperrun>3</ticksperrun>                    <param name="node" type="string">thingDirection</param>                    <param name="learnable.baseLevelActivation" type="double">0.0</param>                    <param name="learnable.baseLevelRemovalThreshold" type="double">-1.0</param>                    <param name="learnable.baseLevelDecayStrategy" type="string">defaultDecay</param>                    <param name="learnable.baseLevelExciteStrategy" type="string">defaultExcite</param>                    <param name="learnable.totalActivationStrategy" type="string">DefaultTotalActivationStrategy</param>                </task>                <task name="ThingToGetDetector">                    <tasktype>ThingToGetDetector</tasktype>                    <ticksperrun>3</ticksperrun>                    <param name="node" type="string">thingToGet</param>                    <param name="learnable.baseLevelActivation" type="double">0.0</param>                    <param name="learnable.baseLevelRemovalThreshold" type="double">-1.0</param>                    <param name="learnable.baseLevelDecayStrategy" type="string">defaultDecay</param>                    <param name="learnable.baseLevelExciteStrategy" type="string">defaultExcite</param>                    <param name="learnable.totalActivationStrategy" type="string">DefaultTotalActivationStrategy</param>                </task>                <task name="ThingCollidedDetector">                    <tasktype>ThingCollidedDetector</tasktype>                    <ticksperrun>3</ticksperrun>                    <param name="node" type="string">thingCollided</param>                    <param name="learnable.baseLevelActivation" type="double">0.0</param>                    <param name="learnable.baseLevelRemovalThreshold" type="double">-1.0</param>                    <param name="learnable.baseLevelDecayStrategy" type="string">defaultDecay</param>                    <param name="learnable.baseLevelExciteStrategy" type="string">defaultExcite</param>                    <param name="learnable.totalActivationStrategy" type="string">DefaultTotalActivationStrategy</param>                </task>                <task name="WallFrontDetector">                    <tasktype>WallFrontDetector</tasktype>                    <ticksperrun>3</ticksperrun>                    <param name="node" type="string">wallFront</param>                    <param name="learnable.baseLevelActivation" type="double">0.0</param>                    <param name="learnable.baseLevelRemovalThreshold" type="double">-1.0</param>                    <param name="learnable.baseLevelDecayStrategy" type="string">defaultDecay</param>                    <param name="learnable.baseLevelExciteStrategy" type="string">defaultExcite</param>                    <param name="learnable.totalActivationStrategy" type="string">DefaultTotalActivationStrategy</param>                </task>                <task name="RandomDetector">                    <tasktype>RandomDetector</tasktype>                    <ticksperrun>3</ticksperrun>                    <param name="node" type="string">random</param>                    <param name="learnable.baseLevelActivation" type="double">0.0</param>                    <param name="learnable.baseLevelRemovalThreshold" type="double">-1.0</param>                    <param name="learnable.baseLevelDecayStrategy" type="string">defaultDecay</param>                    <param name="learnable.baseLevelExciteStrategy" type="string">defaultExcite</param>                    <param name="learnable.totalActivationStrategy" type="string">DefaultTotalActivationStrategy</param>                </task>                <task name="RotateDetector">                    <tasktype>RotateDetector</tasktype>                    <ticksperrun>3</ticksperrun>                    <param name="node" type="string">rotate</param>                    <param name="learnable.baseLevelActivation" type="double">0.0</param>                    <param name="learnable.baseLevelRemovalThreshold" type="double">-1.0</param>                    <param name="learnable.baseLevelDecayStrategy" type="string">defaultDecay</param>                    <param name="learnable.baseLevelExciteStrategy" type="string">defaultExcite</param>                    <param name="learnable.totalActivationStrategy" type="string">DefaultTotalActivationStrategy</param>                </task>                <task name="DeliveryDetector">                    <tasktype>DeliveryDetector</tasktype>                    <ticksperrun>3</ticksperrun>                    <param name="node" type="string">delivery</param>                    <param name="learnable.baseLevelActivation" type="double">0.0</param>                    <param name="learnable.baseLevelRemovalThreshold" type="double">-1.0</param>                    <param name="learnable.baseLevelDecayStrategy" type="string">defaultDecay</param>                    <param name="learnable.baseLevelExciteStrategy" type="string">defaultExcite</param>                    <param name="learnable.totalActivationStrategy" type="string">DefaultTotalActivationStrategy</param>                </task>            </initialTasks>            <initializerclass>edu.memphis.ccrg.lida.pam.BasicPamInitializer</initializerclass>        </module>        <module name="Workspace">            <class>edu.memphis.ccrg.lida.workspace.WorkspaceImpl</class>            <submodules>                <module name="PerceptualBuffer">                    <class>edu.memphis.ccrg.lida.workspace.workspacebuffers.WorkspaceBufferImpl</class>                    <taskspawner>defaultTS</taskspawner>                </module>                <module name="CurrentSituationalModel">                    <class>edu.memphis.ccrg.lida.workspace.workspacebuffers.WorkspaceBufferImpl</class>                    <taskspawner>defaultTS</taskspawner>                </module>                <module name="BroadcastQueue">                    <class>edu.memphis.ccrg.lida.workspace.workspacebuffers.BroadcastQueueImpl</class>                    <param name="workspace.broadcastQueueCapacity" type="int">20 </param>                    <taskspawner>defaultTS</taskspawner>                </module>            </submodules>            <taskspawner>defaultTS</taskspawner>            <initialTasks>                <task name="CueBackgroundTask">                    <tasktype>CueBackgroundTask</tasktype>                    <ticksperrun>15</ticksperrun>                    <param name="workspace.actThreshold"  type="double">0.4</param>                    <param name="workspace.cueingThreshold"  type="double">0.4</param>                    <param name="learnable.baseLevelActivation" type="double">0.0</param>                    <param name="learnable.baseLevelRemovalThreshold" type="double">-1.0</param>                    <param name="learnable.baseLevelDecayStrategy" type="string">defaultDecay</param>                    <param name="learnable.baseLevelExciteStrategy" type="string">defaultExcite</param>                    <param name="learnable.totalActivationStrategy" type="string">Def
