=== eduardofroes/LidaWithWorldServer3D/configs/LidaFactories.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://ccrg.cs.memphis.edu/LidaFactories" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://ccrg.cs.memphis.edu/LidaFactories">
    <complexType name="strategydef">
    	<sequence>
    		<element name="class" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="param" type="tns:param" maxOccurs="unbounded"
    			minOccurs="0">
    		</element>
    	</sequence>
    	<attribute name="name" type="string" use="required"></attribute>
    	<attribute name="type" use="optional">
    		<simpleType>
    			<restriction base="string">
    				<enumeration value="excite"></enumeration>
    				<enumeration value="decay"></enumeration>
    				<enumeration value="propagation"></enumeration>
    				<enumeration value="other"></enumeration>
    			</restriction>
    		</simpleType>
    	</attribute>
    	<attribute name="flyweight" type="boolean" use="optional"></attribute>
    </complexType>
    <complexType name="associatedmodule">
       <simpleContent>
      <extension base="string">
    	<attribute name="function" type="string" use="optional"></attribute>
      </extension>
    </simpleContent>
    </complexType>


    <complexType name="linkabledef">
    	<sequence>
    		<element name="class" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="defaultstrategy" type="string"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    		<element name="param" type="tns:param" maxOccurs="unbounded"
    			minOccurs="0">
    		</element>
    	</sequence>
    	<attribute name="name" type="string" use="required"></attribute>
    </complexType>


    <complexType name="param">
    	<simpleContent>
    		<extension base="string">
    			<attribute name="name" type="string" use="required"></attribute>
    			<attribute name="type" use="optional">
    				<simpleType>
    					<restriction base="string">
    						<enumeration value="int"></enumeration>
    						<enumeration value="double"></enumeration>
    						<enumeration value="string"></enumeration>
    						<enumeration value="boolean"></enumeration>
    					</restriction>
    				</simpleType>
    			</attribute>
    		</extension>
    	</simpleContent>
    </complexType>



    <element name="LidaFactories" type="tns:LidaFactories"></element>
    
    <complexType name="LidaFactories">
    	<sequence>
    		<element name="strategies" type="tns:strategies" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="nodes" type="tns:nodes" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="links" type="tns:links" maxOccurs="1"
    			minOccurs="0">
    		</element>
    		<element name="tasks" type="tns:tasks" maxOccurs="1" minOccurs="0"></element>
    	</sequence>
    </complexType>
    
    <complexType name="nodes">
    	<sequence>
    		<element name="node" type="tns:linkabledef" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="links">
    	<sequence>
    		<element name="link" type="tns:linkabledef" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="strategies">
    	<sequence>
    		<element name="strategy" type="tns:strategydef" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="taskdef">
    	<annotation>
    		<documentation>
    			Refers to definitions of FrameworkTasks including FeatureDetectors, SBCodelets and
    			AttentionCodelets
    		</documentation>
    	</annotation>
    	<sequence>
    		<element name="class" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
            <element name="ticksperrun" type="int" maxOccurs="1" minOccurs="1"></element>
            <element name="defaultstrategy" type="string"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    		<element name="associatedmodule" type="tns:associatedmodule"
    			maxOccurs="unbounded" minOccurs="0">
    		</element>
    		<element name="param" type="tns:param" maxOccurs="unbounded"
    			minOccurs="0">
    		</element>
    	</sequence>
    	<attribute name="name" type="string" use="required"></attribute>
    </complexType>

    <complexType name="tasks">
    	<sequence>
    		<element name="task" type="tns:taskdef" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>

</schema>

=== eduardofroes/LidaWithWorldServer3D/experimentsExecution/configs/factoryData.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright (c) 2009, 2011 The University of Memphis.  All rights reserved. 
    This program and the accompanying materials are made available 
    under the terms of the LIDA Software Framework Non-Commercial License v1.0 
    which accompanies this distribution, and is available at
    http://ccrg.cs.memphis.edu/assets/papers/2010/LIDA-framework-non-commercial-v1.0.pdf
 -->
<LidaFactories xmlns="http://ccrg.cs.memphis.edu/LidaFactories"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://ccrg.cs.memphis.edu/LidaFactories LidaFactories.xsd ">
    <strategies>
        <strategy flyweight="true" name="defaultExcite" type="excite">
            <class>edu.memphis.ccrg.lida.framework.strategies.LinearExciteStrategy
            </class>
            <param name="m" type="double">1.0</param>
        </strategy>
        <strategy flyweight="true" name="defaultDecay" type="decay">
            <class>edu.memphis.ccrg.lida.framework.strategies.LinearDecayStrategy
            </class>
            <param name="m" type="double">0.02</param>
        </strategy>
        <strategy flyweight="true" name="slowExcite" type="excite">
            <class>edu.memphis.ccrg.lida.framework.strategies.LinearExciteStrategy
            </class>
            <param name="m" type="double">0.000000001</param>
        </strategy>
        <strategy flyweight="true" name="slowDecay" type="decay">
            <class>edu.memphis.ccrg.lida.framework.strategies.LinearDecayStrategy
            </class>
            <param name="m" type="double">0.000000001</param>
        </strategy>
        <strategy flyweight="true" name="pamDefaultExcite" type="excite">
            <class>edu.memphis.ccrg.lida.framework.strategies.LinearExciteStrategy
            </class>
            <param name="m" type="double">0.000000001</param>
        </strategy>
        <strategy flyweight="true" name="pamDefaultDecay" type="decay">
            <class>edu.memphis.ccrg.lida.framework.strategies.LinearDecayStrategy
            </class>
            <param name="m" type="double">0.000000001</param>
        </strategy>
        <strategy flyweight="true" name="coalitionDecay" type="decay">
            <class>edu.memphis.ccrg.lida.framework.strategies.LinearDecayStrategy
            </class>
            <param name="m" type="double">0.01</param>
        </strategy>
        <strategy flyweight="true" name="DefaultTotalActivation" type="other">
            <class>edu.memphis.ccrg.lida.framework.strategies.DefaultTotalActivationStrategy
            </class>
        </strategy>
        <strategy flyweight="true" name="BasicSchemeActivationStrategy" type="other">
            <class>edu.memphis.ccrg.lida.proceduralmemory.BasicSchemeActivationStrategy
            </class>
            <param name="schemeSelectionThreshold" type="double">0.5</param>
        </strategy>
    </strategies>
    <nodes>
        <node name="NodeImpl">
            <class>edu.memphis.ccrg.lida.framework.shared.NodeImpl</class>
            <defaultstrategy>defaultDecay</defaultstrategy>
            <defaultstrategy>defaultExcite</defaultstrategy>
        </node>
        <node name="PamNodeImpl">
            <class>edu.memphis.ccrg.lida.pam.PamNodeImpl</class>
            <defaultstrategy>defaultDecay</defaultstrategy>
            <defaultstrategy>defaultExcite</defaultstrategy>
            <param name="learnable.baseLevelDecayStrategy" type="string">slowDecay</param>
            <param name="learnable.baseLevelExciteStrategy" type="string">slowExcite</param>
            <param name="learnable.baseLevelRemovalThreshold" type="double">0.0</param>
            <param name="learnable.baseLevelActivation" type="double">0.1</param>
            <param name="learnable.totalActivationStrategy" type="string">DefaultTotalActivationStrategy</param>
        </node>
    </nodes>
    <links>
        <link name="LinkImpl">
            <class>edu.memphis.ccrg.lida.framework.shared.LinkImpl</class>
            <defaultstrategy>defaultDecay</defaultstrategy>
            <defaultstrategy>defaultExcite</defaultstrategy>
        </link>
        <link name="PamLinkImpl">
            <class>edu.memphis.ccrg.lida.pam.PamLinkImpl</class>
            <defaultstrategy>defaultDecay</defaultstrategy>
            <defaultstrategy>defaultExcite</defaultstrategy>
            <param name="learnable.baseLevelDecayStrategy" type="string">slowDecay</param>
            <param name="learnable.baseLevelExciteStrategy" type="string">slowExcite</param>
            <param name="learnable.baseLevelRemovalThreshold" type="double">0.0</param>
            <param name="learnable.baseLevelActivation" type="double">0.1</param>
            <param name="learnable.totalActivationStrategy" type="string">DefaultTotalActivationStrategy</param>
        </link>
    </links>
    <tasks>
        <task name="SensoryMemoryBackgroundTask">
            <class>edu.memphis.ccrg.lida.sensorymemory.SensoryMemoryBackgroundTask</class>
            <ticksperrun>5</ticksperrun>
            <associatedmodule>SensoryMemory</associatedmodule>
            <param name="learnable.baseLevelDecayStrategy" type="string">slowDecay</param>
            <param name="learnable.baseLevelExciteStrategy" type="string">slowExcite</param>
            <param name="learnable.baseLevelRemovalThreshold" type="double">0.0</param>
            <param name="learnable.baseLevelActivation" type="double">0.1</param>
            <param name="learnable.totalActivationStrategy" type="string">DefaultTotalActivationStrategy</param>
        </task>
        <task name="BasicDetector">
            <class>edu.memphis.ccrg.lida.pam.tasks.BasicDetectionAlgorithm</class>
            <ticksperrun>3</ticksperrun>
            <associatedmodule>SensoryMemory</associatedmodule>
            <associatedmodule>PerceptualAssociativeMemory</associatedmodule>
        </task>
        <task name="ThingDirectionDetector">
            <class>detectors.ThingDirectionDetector</class>
            <ticksperrun>3</ticksperrun>
            <associatedmodule>SensoryMemory</associatedmodule>
            <associatedmodule>PerceptualAssociativeMemory</associatedmodule>
        </task>
        <task name="ThingToGetDetector">
            <class>detectors.ThingToGetDetector</class>
            <ticksperrun>3</ticksperrun>
            <associatedmodule>SensoryMemory</associatedmodule>
            <associatedmodule>PerceptualAssociativeMemory</associatedmodule>
        </task>
        <task name="ThingCollidedDetector">
            <class>detectors.ThingCollidedDetector</class>
            <ticksperrun>3</ticksperrun>
            <associatedmodule>SensoryMemory</associatedmodule>
            <associatedmodule>PerceptualAssociativeMemory</associatedmodule>
        </task>

        <task name="WallFrontDetector">
            <class>detectors.WallFrontDetector</class>
            <ticksperrun>3</ticksperrun>
            <associatedmodule>SensoryMemory</associatedmodule>
            <associatedmodule>PerceptualAssociativeMemory</associatedmodule>
        </task>
        
        <task name="RotateDetector">
            <class>detectors.RotateDetector</class>
            <ticksperrun>3</ticksperrun>
            <associatedmodule>SensoryMemory</associatedmodule>
            <associatedmodule>PerceptualAssociativeMemory</associatedmodule>
        </task>

        <task name="DeliveryDetector">
            <class>detectors.DeliveryDetector</class>
            <ticksperrun>3</ticksperrun>
            <associatedmodule>SensoryMemory</associatedmodule>
            <associatedmodule>PerceptualAssociativeMemory</associatedmodule>
        </task>
        
        <task name="RandomDetector">
            <class>detectors.RandomDetector</class>
            <ticksperrun>3</ticksperrun>
            <associatedmodule>SensoryMemory</associatedmodule>
            <associatedmodule>PerceptualAssociativeMemory</associatedmodule>
        </task>
        
        <task name="BasicAttentionCodelet">
            <class>edu.memphis.ccrg.lida.attentioncodelets.BasicAttentionCodelet
            </class>
            <ticksperrun>20</ticksperrun>
            <associatedmodule function="TO_READ_FROM">CurrentSituationalModel</associatedmodule>
            <associatedmodule function="TO_WRITE_TO">GlobalWorkspace</associatedmodule>
            <param name="refractoryPeriod" type="int">50</param>
            <param name="coalitionDecayStrategy" type="string">coalitionDecay</param>
        </task>
        <task name="DefaultAttentionCodelet">
            <class>edu.memphis.ccrg.lida.attentioncodelets.DefaultAttentionCodelet
            </class>
            <ticksperrun>20</ticksperrun>
            <associatedmodule function="TO_READ_FROM">CurrentSituationalModel</associatedmodule>
            <associatedmodule function="TO_WRITE_TO">GlobalWorkspace</associatedmodule>
            <param name="refractoryPeriod" type="int">50</param>
            <param name="coalitionDecayStrategy" type="string">coalitionDecay</param>
        </task>
        <task name="NeighborhoodAttentionCodelet">
            <class>edu.memphis.ccrg.lida.attentioncodelets.NeighborhoodAttentionCodelet
            </class>
            <ticksperrun>20</ticksperrun>
            <associatedmodule function="TO_READ_FROM">CurrentSituationalModel</associatedmodule>
            <associatedmodule function="TO_WRITE_TO">GlobalWorkspace</associatedmodule>
            <param name="refractoryPeriod" type="int">50</param>
            <param name="coalitionDecayStrategy" type="string">coalitionDecay</param>
        </task>
        <task name="CueBackgroundTask">
            <class>edu.memphis.ccrg.lida.workspace.CueBackgroundTask</class>
            <ticksperrun>15</ticksperrun>
